site_name: Spaceship
site_author: Spaceship Team
site_url: https://spaceship-prompt.sh
site_description: Minimalistic, powerful and extremely customizable Zsh prompt

copyright: "Copyright &copy; 2021 Denys Dovhan"

repo_url: https://github.com/spaceship-prompt/spaceship-prompt
repo_name: spaceship-prompt

theme:
  name: material
  custom_dir: docs/overrides
  logo: //spaceship-prompt.github.io/brand/spaceship-no-letters.svg
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: spaceship
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Customization:
      - Sections:
        - Prompt character (char): sections/char.md
        - Hostname (host): sections/host.md
        - Directory (dir): sections/dir.md
        - Line separator (line_sep): sections/line_sep.md
        - Async (async): sections/async.md
        - Battery (battery): sections/battery.md
        - Execution time (exec_time): sections/exec_time.md
        - Exit code (exit_code): sections/exit_code.md
        - Git (git): sections/git.md
        - Mercurial (hg): sections/hg.md
        - Package (package): sections/package.md
        - Node.js (node): sections/node.md
        - Elm (elm): sections/elm.md
        - Elixir (elixir): sections/elixir.md
        - Go (golang): sections/golang.md
        - PHP (php): sections/php.md
        - Haskell (haskell): sections/haskell.md
        - Java (java): sections/java.md
        - Julia (julia): sections/julia.md
        - Docker (docker): sections/docker.md
        - Amazon Web Services (aws): sections/aws.md
        - Google Cloud Platform (gcloud): sections/gcloud.md
        - Conda virtualenv (conda): sections/conda.md
        - .NET (dotnet): sections/dotnet.md
  - API: api.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - attr_list
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spaceship-prompt/spaceship-prompt
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SpaceshipPrompt
    - icon: fontawesome/brands/discord
      link: https://discord.gg/NTQWz8Dyt9

extra_css:
  - assets/styles.css

plugins:
  - search:
      lang:
        - en
        - ru
        - zh
  - i18n:
      default_language: en
      languages:
        en: English
        uk: Українська
        zh: 简体中文
