[build]
  base = "."
  publish = "site"
  command = "mkdocs build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF docs mkdocs.yml requirements.txt crowdin.yml"

# StandWithUkraine
[[redirects]]
  from = "/*"
  to = "https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/ToRussianPeople.md"
  conditions = {Country = ["RU", "BY"]}
