[build]
  base = "."
  publish = "site"
  command = "mkdocs build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF docs mkdocs.yml requirements.txt crowdin.yml netlify.toml"

# StandWithUkraine
[[redirects]]
  from = "https://spaceship-prompt.sh/*"
  to = "https://stand-with-ukraine.pp.ua/ToRussianPeople.html"
  status = 301
  force = true
  conditions = {Country = ["RU", "BY"]}

[[redirects]]
  from = "/api"
  to = "/api/environent"

[[redirects]]
  from = "/options"
  to = "/config/intro/"
