name: homebrew
on:
  push:
    tags:
      - "v*"

jobs:
  homebrew:
    name: Bump Homebrew
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: 🍺 Bump Homebrew Formula
        uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: spaceship
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GITHUB_PAT }}
